In [1]:
# NMEA Parser
import pandas as pd
import pynmea2

In [2]:
df_org = pd.read_json('nmea.json')
df_org

,topic,sequence,log_time,publish_time,data
0,rise/v0/boatswain/pubsub/raw_string/rutx,0,2024-06-15 15:40:50.907141447,2024-06-15 15:40:50.896004438,{'timestamp': '2024-06-15T15:40:50.895074010Z'...
1,rise/v0/boatswain/pubsub/raw_string/rutx,0,2024-06-15 15:40:50.908050299,2024-06-15 15:40:50.897454739,{'timestamp': '2024-06-15T15:40:50.896772436Z'...
2,rise/v0/boatswain/pubsub/raw_string/rutx,0,2024-06-15 15:40:50.908384800,2024-06-15 15:40:50.898829460,{'timestamp': '2024-06-15T15:40:50.898102617Z'...
3,rise/v0/boatswain/pubsub/raw_string/rutx,0,2024-06-15 15:40:50.908675432,2024-06-15 15:40:50.900180817,{'timestamp': '2024-06-15T15:40:50.899484925Z'...
4,rise/v0/boatswain/pubsub/raw_string/rutx,0,2024-06-15 15:40:50.908916235,2024-06-15 15:40:50.900638819,{'timestamp': '2024-06-15T15:40:50.900486806Z'...
...,...,...,...,...,...
424,rise/v0/boatswain/pubsub/raw_string/rutx,0,2024-06-15 15:41:19.933615685,2024-06-15 15:41:19.909509897,{'timestamp': '2024-06-15T15:41:19.908966800Z'...
425,rise/v0/boatswain/pubsub/raw_string/rutx,0,2024-06-15 15:41:19.934429169,2024-06-15 15:41:19.910702705,{'timestamp': '2024-06-15T15:41:19.910113545Z'...
426,rise/v0/boatswain/pubsub/raw_string/rutx,0,2024-06-15 15:41:19.935860634,2024-06-15 15:41:19.911830187,{'timestamp': '2024-06-15T15:41:19.911217522Z'...
427,rise/v0/boatswain/pubsub/raw_string/rutx,0,2024-06-15 15:41:19.937097073,2024-06-15 15:41:19.912941933,{'timestamp': '2024-06-15T15:41:19.912363524Z'...
428,rise/v0/boatswain/pubsub/raw_string/rutx,0,2024-06-15 15:41:19.938378811,2024-06-15 15:41:19.914089680,{'timestamp': '2024-06-15T15:41:19.913445755Z'...

In [3]:
df = df_org[['topic']].join(df_org['data'].apply(pd.Series))
df['timestamp'] = pd.to_datetime(df['timestamp'])
df

,topic,timestamp,value
0,rise/v0/boatswain/pubsub/raw_string/rutx,2024-06-15 15:40:50.895074010+00:00,"$GLGSV,3,1,11,78,26,026,,70,66,239,,86,47,307,..."
1,rise/v0/boatswain/pubsub/raw_string/rutx,2024-06-15 15:40:50.896772436+00:00,"$GLGSV,3,2,11,79,18,081,,69,42,060,,84,08,170,..."
2,rise/v0/boatswain/pubsub/raw_string/rutx,2024-06-15 15:40:50.898102617+00:00,"$GLGSV,3,3,11,85,54,208,,71,16,239,,68,,,,1*79..."
3,rise/v0/boatswain/pubsub/raw_string/rutx,2024-06-15 15:40:50.899484925+00:00,"$GPGSV,7,1,25,02,18,160,,03,73,120,,04,52,191,..."
4,rise/v0/boatswain/pubsub/raw_string/rutx,2024-06-15 15:40:50.900486806+00:00,"$GPGSV,7,2,25,09,18,216,,11,00,314,,12,11,340,..."
...,...,...,...
424,rise/v0/boatswain/pubsub/raw_string/rutx,2024-06-15 15:41:19.908966800+00:00,"$GNGNS,154119.91,,,,,NNN,,,,,,*32\r\n"
425,rise/v0/boatswain/pubsub/raw_string/rutx,2024-06-15 15:41:19.910113545+00:00,"$GPVTG,,T,,M,,N,,K,N*2C\r\n"
426,rise/v0/boatswain/pubsub/raw_string/rutx,2024-06-15 15:41:19.911217522+00:00,"$GPRMC,,V,,,,,,,,,,N*53\r\n"
427,rise/v0/boatswain/pubsub/raw_string/rutx,2024-06-15 15:41:19.912363524+00:00,"$GPGSA,A,1,,,,,,,,,,,,,,,*1E\r\n"
428,rise/v0/boatswain/pubsub/raw_string/rutx,2024-06-15 15:41:19.913445755+00:00,"$GNGSA,A,1,,,,,,,,,,,,,,,*00\r\n"

In [4]:
df['first_segment'] = df['value'].str.split(',').str[0]
df.first_segment.unique()

array(['$GLGSV', '$GPGSV', '$GPGGA', '$GNGNS', '$GPVTG', '$GPRMC',
       '$GPGSA', '$GNGSA'], dtype=object)

**Maybe implementing**
- GNGNS: GNSS fix data
- GPVTG: Track made good and ground speed
- GPGGA: GPS fix
- GPRMC: GPS specific information
----
**Not to be used**
- GLGSV: Glonass (satellites in view identifies the number of Satelit View (SV) in view, the PRN numbers, elevations, azimuths, and SNR value)
- GPGSV: GPS satellites in view
- GPGSA: GPS DOP and active satellites
- GNGSA: GPS DOP and active satellites

In [7]:
# Get nmea type
nmea_sentence = "$GPGGA,123519,4807.038,N,01131.000,E,1,08,0.9,545.4,M,46.9,M,,*47"
nmea_sentence.split(',')[0]

'$GPGGA'

In [5]:
# Example NMEA sentence
nmea_sentence = "$GPGGA,123519,4807.038,N,01131.000,E,1,08,0.9,545.4,M,46.9,M,,*47"
nmea_sentence = "$GNGNS,154119.91,,,,,NNN,,,,,,*32\r\n"

# Parse the NMEA sentence
parsed_sentence = pynmea2.parse(nmea_sentence)

# Access the parsed data
# latitude = parsed_sentence.latitude
# longitude = parsed_sentence.longitude
# altitude = parsed_sentence.altitude

# Print the parsed data
# print("Latitude:", latitude)
# print("Longitude:", longitude)
# print("Altitude:", altitude)
parsed_sentence

<GNS(timestamp=datetime.time(15, 41, 19, 910000, tzinfo=datetime.timezone.utc), lat='', lat_dir='', lon='', lon_dir='', mode_indicator='NNN', num_sats='', hdop='', altitude='', geo_sep='', age_gps_data='', diferential='')>

In [15]:


parsed_values = []
for sentence in df['value']:
  parsed_sentence = pynmea2.parse(sentence)
  parsed_values.append(parsed_sentence)

df['parsed_value'] = parsed_values

In [16]:
df

,topic,timestamp,value,first_segment,parsed_value
0,rise/v0/boatswain/pubsub/raw_string/rutx,2024-06-15 15:40:50.895074010+00:00,"$GLGSV,3,1,11,78,26,026,,70,66,239,,86,47,307,...",$GLGSV,"$GLGSV,3,1,11,78,26,026,,70,66,239,,86,47,307,..."
1,rise/v0/boatswain/pubsub/raw_string/rutx,2024-06-15 15:40:50.896772436+00:00,"$GLGSV,3,2,11,79,18,081,,69,42,060,,84,08,170,...",$GLGSV,"$GLGSV,3,2,11,79,18,081,,69,42,060,,84,08,170,..."
2,rise/v0/boatswain/pubsub/raw_string/rutx,2024-06-15 15:40:50.898102617+00:00,"$GLGSV,3,3,11,85,54,208,,71,16,239,,68,,,,1*79...",$GLGSV,"$GLGSV,3,3,11,85,54,208,,71,16,239,,68,,,,1*79"
3,rise/v0/boatswain/pubsub/raw_string/rutx,2024-06-15 15:40:50.899484925+00:00,"$GPGSV,7,1,25,02,18,160,,03,73,120,,04,52,191,...",$GPGSV,"$GPGSV,7,1,25,02,18,160,,03,73,120,,04,52,191,..."
4,rise/v0/boatswain/pubsub/raw_string/rutx,2024-06-15 15:40:50.900486806+00:00,"$GPGSV,7,2,25,09,18,216,,11,00,314,,12,11,340,...",$GPGSV,"$GPGSV,7,2,25,09,18,216,,11,00,314,,12,11,340,..."
...,...,...,...,...,...
424,rise/v0/boatswain/pubsub/raw_string/rutx,2024-06-15 15:41:19.908966800+00:00,"$GNGNS,154119.91,,,,,NNN,,,,,,*32\r\n",$GNGNS,"$GNGNS,154119.91,,,,,NNN,,,,,,*32"
425,rise/v0/boatswain/pubsub/raw_string/rutx,2024-06-15 15:41:19.910113545+00:00,"$GPVTG,,T,,M,,N,,K,N*2C\r\n",$GPVTG,"$GPVTG,,T,,M,,N,,K,N*2C"
426,rise/v0/boatswain/pubsub/raw_string/rutx,2024-06-15 15:41:19.911217522+00:00,"$GPRMC,,V,,,,,,,,,,N*53\r\n",$GPRMC,"$GPRMC,,V,,,,,,,,,,N*53"
427,rise/v0/boatswain/pubsub/raw_string/rutx,2024-06-15 15:41:19.912363524+00:00,"$GPGSA,A,1,,,,,,,,,,,,,,,*1E\r\n",$GPGSA,"$GPGSA,A,1,,,,,,,,,,,,,,,*1E"
428,rise/v0/boatswain/pubsub/raw_string/rutx,2024-06-15 15:41:19.913445755+00:00,"$GNGSA,A,1,,,,,,,,,,,,,,,*00\r\n",$GNGSA,"$GNGSA,A,1,,,,,,,,,,,,,,,*00"